dattran900190/BarberHouse-DATN

- app/Http/Controllers/ServiceController.php
- app/Http/Requests/ServiceRequest.php
- app/Models/Service.php
- database/factories/ServiceFactory.php
- resources/views/admin/services/create.blade.php
- resources/views/admin/services/edit.blade.php
- resources/views/admin/services/index.blade.php
- resources/views/admin/services/show.blade.php
- routes/web.php
> CRUD cho dịch vụ

- app/Http/Controllers/ProductController.php
- app/Models/Product.php
- app/Models/ProductCategory.php
- app/Models/ProductImage.php
- app/Models/ProductVariant.php
- app/Models/Volume.php
- config/adminlte.php
- database/factories/ProductCategoryFactory.php
- database/factories/ProductFactory.php
- database/factories/ProductImageFactory.php
- database/factories/ProductVariantFactory.php
- database/factories/VolumeFactory.php
- database/seeders/ProductSeeder.php
- resources/views/admin/products/create.blade.php
- resources/views/admin/products/edit.blade.php
- resources/views/admin/products/index.blade.php
- resources/views/admin/products/show.blade.php
- routes/web.php
Thêm chức năng crud hiển thị chi tiết sản phẩm
> Thêm chức năng crud hiển thị chi tiết sản phẩm

- app/Http/Controllers/ProductController.php
- app/Http/Requests/ProductRequest.php
- resources/views/admin/products/create.blade.php
- resources/views/admin/products/edit.blade.php
- routes/web.php
Fix  validate và giao diện thêm mới
> Fix  validate và giao diện thêm mới

- public/css/client.css
- public/js/client.js
- resources/views/client/booking.blade.php
- resources/views/client/branch.blade.php
- resources/views/client/cart.blade.php
- resources/views/client/checkout.blade.php
- resources/views/client/detailBranch.blade.php
- resources/views/client/detailPost.blade.php
- resources/views/client/detailProduct.blade.php
- resources/views/client/home.blade.php
- resources/views/client/listBarber.blade.php
- resources/views/client/post.blade.php
- resources/views/client/product.blade.php
- resources/views/layouts/ClientLayout.blade.php
- resources/views/layouts/blocks/header.blade.php
- routes/web.php
> client list barber

- app/Http/Controllers/Client/AppointmentController.php
- app/Http/Controllers/Client/OrderController.php
- public/css/client.css
- resources/views/client/appointmentHistory.blade.php
- resources/views/client/branch.blade.php
- resources/views/client/detailAppointmentHistory.blade.php
- resources/views/client/detailOrderHistory.blade.php
- resources/views/client/home.blade.php
- resources/views/client/orderHistory.blade.php
- resources/views/emails/pending_booking.blade.php
- resources/views/layouts/ClientLayout.blade.php
- resources/views/layouts/blocks/header.blade.php
- routes/web.php
client order history + appointment history
> client order history + appointment history

- app/Http/Controllers/Client/WalletController.php
- public/css/client.css
- resources/views/client/appointmentHistory.blade.php
- resources/views/client/detailWallet.blade.php
- resources/views/client/redeem.blade.php
- resources/views/client/wallet.blade.php
- resources/views/client/withdrawal.blade.php
- resources/views/layouts/blocks/header.blade.php
- routes/web.php
> client wallet

- app/Filters/AppointmentCountFilter.php
- app/Http/Controllers/Client/AppointmentController.php
- app/Models/Appointment.php
- app/Providers/AppServiceProvider.php
- public/js/client.js
- resources/js/app.js
- resources/js/bootstrap.js
- resources/views/admin/dashboard.blade.php
- resources/views/layouts/app.blade.php
- resources/views/layouts/partials/sidebar-menu.blade.php
fix select barber in booking client
> fix select barber in booking client

- app/Http/Controllers/AppointmentController.php
- app/Http/Controllers/Client/AppointmentController.php
- app/Http/Requests/AppointmentRequest.php
- public/css/client.css
- public/js/client.js
- resources/views/admin/appointments/edit.blade.php
- resources/views/admin/appointments/index.blade.php
- resources/views/admin/appointments/partial/_actions.blade.php
- resources/views/admin/appointments/partial/_table.blade.php
- resources/views/admin/appointments/show.blade.php
- resources/views/admin/reviews/index.blade.php
- resources/views/admin/users/index.blade.php
- resources/views/client/booking.blade.php
- resources/views/layouts/AdminLayout.blade.php
- resources/views/layouts/blocksAdmin/header.blade.php
- resources/views/layouts/blocksAdmin/includes/link-head.blade.php
- resources/views/layouts/blocksAdmin/sidebar.blade.php
- resources/views/layouts/blocksAdmin/toast/allToast.blade.php
fix thông báo tìm kiếm đặt lịch
> fix thông báo tìm kiếm đặt lịch

- app/Http/Controllers/Client/HomeController.php
- app/Http/Controllers/CustomerImageController.php
- app/Http/Controllers/SettingController.php
- app/Models/CustomerImage.php
- app/Models/Setting.php
- app/Providers/AppServiceProvider.php
- database/migrations/2025_07_16_164227_create_settings_table.php
- database/migrations/2025_07_16_230612_create_customer_images_table.php
- public/css/client.css
- resources/views/admin/barber_schedules/index.blade.php
- resources/views/admin/barber_schedules/show.blade.php
- resources/views/admin/custormer_images/create.blade.php
- resources/views/admin/custormer_images/edit.blade.php
- resources/views/admin/custormer_images/index.blade.php
- resources/views/admin/custormer_images/show.blade.php
- resources/views/admin/promotions/index.blade.php
- resources/views/admin/settings/index.blade.php
- resources/views/client/appointmentHistory.blade.php
- resources/views/client/home.blade.php
- resources/views/client/login.blade.php
- resources/views/client/orderHistory.blade.php
- resources/views/client/register.blade.php
- resources/views/layouts/ClientLayout.blade.php
- resources/views/layouts/blocks/header.blade.php
- resources/views/layouts/blocks/includes/link-foot.blade.php
- resources/views/layouts/blocks/includes/link-head.blade.php
- resources/views/layouts/blocksAdmin/sidebar.blade.php
- routes/web.php
cài đặt chung admin + ảnh khách hàng admin
> cài đặt chung admin + ảnh khách hàng admin

- app/Http/Controllers/Client/OrderController.php
- app/Http/Controllers/OrderController.php
- app/Http/Controllers/UserRedeemedVoucherController.php
- public/js/client.js
- resources/views/admin/products/create.blade.php
- resources/views/admin/user_redeemed_vouchers/index.blade.php
- resources/views/admin/user_redeemed_vouchers/show.blade.php
- resources/views/client/booking.blade.php
- resources/views/client/checkout.blade.php
- resources/views/client/detailProduct.blade.php
- routes/web.php
Cập nhập sửa vocher giao diện chi tiết sản phẩm
> Cập nhập sửa vocher giao diện chi tiết sản phẩm

- app/Http/Controllers/Client/CartController.php
- app/Http/Controllers/Client/ClientProductController.php
- app/Http/Controllers/ProductController.php
- app/Http/Requests/ProductRequest.php
- app/Models/Product.php
- database/migrations/2025_05_12_082428_create_products_table.php
- resources/views/admin/products/create.blade.php
- resources/views/admin/products/edit.blade.php
- resources/views/admin/products/show.blade.php
- resources/views/client/detailProduct.blade.php
Sửa lại biến thể thêm mô tả dài thêm ảnh biến thể ở giao diện
> Sửa lại biến thể thêm mô tả dài thêm ảnh biến thể ở giao diện

- app/Http/Controllers/VolumeController.php
- resources/views/admin/volumes/index.blade.php
- resources/views/client/detailProduct.blade.php
- resources/views/client/home.blade.php
- resources/views/client/product.blade.php
Cập nhập trạng thái khi biến thể tồn kho hết hàng sửa xóa mềm dung tích
> Cập nhập trạng thái khi biến thể tồn kho hết hàng sửa xóa mềm dung tích

- app/Events/OrderStatusUpdated.php
- app/Http/Controllers/OrderController.php
- resources/views/admin/orders/index.blade.php
- resources/views/client/login.blade.php
- resources/views/layouts/ClientLayout.blade.php
> Cập nhập thông báo readtime

- app/Http/Controllers/ProductController.php
- app/Http/Controllers/UserRedeemedVoucherController.php
- app/Http/Controllers/VolumeController.php
- resources/views/admin/products/index.blade.php
- resources/views/admin/products/show-trashed.blade.php
- resources/views/admin/user_redeemed_vouchers/index.blade.php
- resources/views/admin/user_redeemed_vouchers/show.blade.php
- resources/views/admin/volumes/index.blade.php
- routes/web.php
> Sửa lại giao diện thông báo

- app/Http/Controllers/ProductController.php
- public/css/client.css
- resources/views/client/detailProduct.blade.php
> Cập nhập giao diện

- app/Http/Controllers/Client/CartController.php
- app/Models/CartItem.php
- resources/views/client/cart.blade.php
- resources/views/client/detailProduct.blade.php
Cập nhập số lượng tồn kho và fix xóa mềm sản phẩm lỗi ở cart
> Cập nhập số lượng tồn kho và fix xóa mềm sản phẩm lỗi ở cart

- app/Http/Controllers/Client/AppointmentController.php
- app/Http/Controllers/ProductController.php
- resources/views/admin/products/edit.blade.php
- resources/views/client/cart.blade.php
> Cập nhập validate

- resources/views/admin/products/edit.blade.php
- resources/views/client/detailProduct.blade.php
- resources/views/client/home.blade.php
Validate và repponse giao diện
> Validate và repponse giao diện

- app/Http/Controllers/Client/CartController.php
- public/css/client.css
- resources/views/admin/products/index.blade.php
- resources/views/admin/products/show.blade.php
- resources/views/client/cart.blade.php
Cập nhật validate checkout số lượng tồn kho và sửa giao diện
> Cập nhật validate checkout số lượng tồn kho và sửa giao diện

- app/Http/Controllers/VolumeController.php
- resources/views/admin/volumes/create.blade.php
- resources/views/admin/volumes/edit.blade.php
> Sửa validate dung tích

- app/Http/Controllers/Client/AppointmentController.php
- resources/views/client/booking.blade.php
> Sửa email đặt lịch

- app/Http/Controllers/AppointmentController.php
- resources/views/admin/promotions/create.blade.php
> Cập nhập voucher

- app/Http/Controllers/AppointmentController.php
- resources/views/admin/appointments/edit.blade.php
- resources/views/partials/low-products.blade.php
> Sửa voucher

- resources/js/admin.js
- resources/views/admin/orders/index.blade.php
- resources/views/client/detailProduct.blade.php
> Sửa lại chi tiết sản phẩm 

- app/Http/Controllers/ProductController.php
- app/Models/ProductImage.php
- database/migrations/2025_08_27_024547_add_soft_deletes_to_product_images_table.php
- resources/views/layouts/blocksAdmin/includes/link-foot.blade.php
> Sửa giao diện xóa mềm
